Pass language
firstandthird/localization-bar pull request #1
Opened 2017-01-19 08:25 UTC by mturnwall

You can now pass a language in to override the browser's preferred language.

I also added the example page.

2017-01-19 15:02 UTC, jgallen23 requested changes

2017-01-19 15:02 UTC, jgallen23 commented on localization-bar.js
> +    console.log(this.language);
Oops

2017-01-19 15:02 UTC, jgallen23 commented on example/example.js
> +/******/ (function(modules) { // webpackBootstrap
We shouldn't check this in

2017-01-19 15:02 UTC, jgallen23 commented on package.json
> +    "build": "webpack"
Scriptkit already does the building, not sure why we added webpack

2017-01-20 18:45 UTC, mturnwall commented
I removed the console log and the webpack config.

2017-05-10 10:09 UTC, merged